--------------------------------------------------------
--  Fichier créé - mercredi-mai-10-2023   
--------------------------------------------------------
@C:\Users\Zakaria\Desktop\SQL\ENSCOACHS.sql
@C:\Users\Zakaria\Desktop\SQL\TCOACH.sql
@C:\Users\Zakaria\Desktop\SQL\TSALLE.sql
@C:\Users\Zakaria\Desktop\SQL\LOGMNR_EVOLVE_SEQ_.sql
@C:\Users\Zakaria\Desktop\SQL\LOGMNR_UIDS_.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW__ADVSEQ_ID.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__FLAVOR_NAME_S.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT_LOG_SEQUENCE.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__REPPROP_KEY.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__TEMPLATE_OBJECTS_S.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__TEMPLATE_REFGROUPS_S.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__TEMP_OUTPUT_S.sql
@C:\Users\Zakaria\Desktop\SQL\REPCAT__USER_PARM_VALUES_S.sql
@C:\Users\Zakaria\Desktop\SQL\COACH.sql
@C:\Users\Zakaria\Desktop\SQL\LESCOACHS.sql
@C:\Users\Zakaria\Desktop\SQL\SALLE.sql
@C:\Users\Zakaria\Desktop\SQL\AQ_DEF__AQCALL.sql
@C:\Users\Zakaria\Desktop\SQL\AQ_DEF__AQERROR.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_EVALUATIONS.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_EXCEPTIONS.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_FILTER.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_FILTERINSTANCE.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_LOG.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_RECOMMENDATIONS.sql
@C:\Users\Zakaria\Desktop\SQL\MVIEW_WORKLOAD.sql
@C:\Users\Zakaria\Desktop\SQL\PRODUCT_PRIVS.sql
@C:\Users\Zakaria\Desktop\SQL\COACH_DATA_TABLE.sql
@C:\Users\Zakaria\Desktop\SQL\LESCOACHS_DATA_TABLE.sql
@C:\Users\Zakaria\Desktop\SQL\LESSALLES_DATA_TABLE.sql
@C:\Users\Zakaria\Desktop\SQL\SALLE_DATA_TABLE.sql
@C:\Users\Zakaria\Desktop\SQL\SEANCES_DATA_TABLE.sql
@C:\Users\Zakaria\Desktop\SQL\SYS_C003997.sql
@C:\Users\Zakaria\Desktop\SQL\SYS_C003995.sql
@C:\Users\Zakaria\Desktop\SQL\Q3.sql
@C:\Users\Zakaria\Desktop\SQL\Q5.sql
@C:\Users\Zakaria\Desktop\SQL\Q7.sql
@C:\Users\Zakaria\Desktop\SQL\Q7_1.sql
@C:\Users\Zakaria\Desktop\SQL\Q3_1.sql
@C:\Users\Zakaria\Desktop\SQL\ORA__SYS_REP_AUTH.sql
@C:\Users\Zakaria\Desktop\SQL\DBMS_REPCAT_AUTH.sql
@C:\Users\Zakaria\Desktop\SQL\DBMS_REPCAT_AUTH.sql
@C:\Users\Zakaria\Desktop\SQL\COL.sql
@C:\Users\Zakaria\Desktop\SQL\PUBLICSYN.sql
@C:\Users\Zakaria\Desktop\SQL\SYSFILES.sql
@C:\Users\Zakaria\Desktop\SQL\TABQUOTAS.sql
@C:\Users\Zakaria\Desktop\SQL\DEF__AQERROR.sql
@C:\Users\Zakaria\Desktop\SQL\DEF__AQCALL.sql
@C:\Users\Zakaria\Desktop\SQL\DEF__AQCALL_1.sql
@C:\Users\Zakaria\Desktop\SQL\DEF__AQERROR_1.sql
@C:\Users\Zakaria\Desktop\SQL\LESSALLES_CONSTRAINT.sql
